import { cp, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const rootDir = process.cwd();
const distDir = path.join(rootDir, "dist");
const holidaysUrl = "https://www8.cao.go.jp/chosei/shukujitsu/syukujitsu.csv";
const sourceOnlyEntries = new Set([
  ".git",
  "dist",
  "node_modules",
  "package-lock.json",
  "package.json",
  "scripts",
  "workers",
  "wrangler.toml"
]);

async function fetchJapaneseHolidays() {
  const response = await fetch(holidaysUrl, {
    headers: {
      "user-agent": "sssoftware-cloudflare-pages-build"
    }
  });

  if (!response.ok) {
    throw new Error(`Failed to fetch holidays CSV: ${response.status} ${response.statusText}`);
  }

  const bytes = await response.arrayBuffer();
  const csv = new TextDecoder("shift_jis").decode(bytes);
  const holidays = {};

  for (const rawLine of csv.split(/\r?\n/)) {
    const line = rawLine.trim();
    const match = line.match(/^(\d{4})\/(\d{1,2})\/(\d{1,2}),(.+)$/);
    if (!match) continue;

    const [, year, month, day, name] = match;
    const dateKey = `${year}-${month.padStart(2, "0")}-${day.padStart(2, "0")}`;
    holidays[dateKey] = name.trim();
  }

  const count = Object.keys(holidays).length;
  if (count < 100) {
    throw new Error(`Parsed too few holiday rows: ${count}`);
  }

  return holidays;
}

function toHolidayObjectSource(holidays, indent = "    ") {
  const entries = Object.entries(holidays);

  return [
    `${indent}const japaneseHolidays = {`,
    ...entries.map(([dateKey, name], index) => {
      const comma = index === entries.length - 1 ? "" : ",";
      return `${indent}  ${JSON.stringify(dateKey)}: ${JSON.stringify(name)}${comma}`;
    }),
    `${indent}};`
  ].join("\n");
}

async function copyStaticSite() {
  await rm(distDir, { recursive: true, force: true });
  await mkdir(distDir, { recursive: true });

  const entries = await readdir(rootDir, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name.startsWith(".")) continue;
    if (sourceOnlyEntries.has(entry.name)) continue;
    if (entry.name.toLowerCase().startsWith("readme")) continue;

    const sourcePath = path.join(rootDir, entry.name);
    const targetPath = path.join(distDir, entry.name);
    await cp(sourcePath, targetPath, { recursive: true });
  }
}

async function updateIndexHtml(holidays) {
  const indexPath = path.join(distDir, "index.html");
  let html = await readFile(indexPath, "utf8");
  const holidaysSource = toHolidayObjectSource(holidays);
  const holidayBlockPattern = /    const japaneseHolidays = \{[\s\S]*?\n    \};/;

  if (holidayBlockPattern.test(html)) {
    html = html.replace(holidayBlockPattern, holidaysSource);
    await writeFile(indexPath, html);
    console.log("Updated japaneseHolidays block in dist/index.html.");
  } else {
    console.warn("No japaneseHolidays block found in index.html. Wrote holidays.generated.js only.");
  }

  const generatedJs = [
    "// Generated by scripts/build-site.mjs from the Cabinet Office Japan holidays CSV.",
    `window.sssoftwareJapaneseHolidays = ${JSON.stringify(holidays, null, 2)};`,
    ""
  ].join("\n");
  await writeFile(path.join(distDir, "holidays.generated.js"), generatedJs);
}

const holidays = await fetchJapaneseHolidays();
await copyStaticSite();
await updateIndexHtml(holidays);

const holidayDates = Object.keys(holidays);
console.log(`Generated site in dist with ${holidayDates.length} holiday rows.`);
console.log(`Holiday range: ${holidayDates[0]} to ${holidayDates[holidayDates.length - 1]}`);
